## Intro to numpy, short for numerical python

In [1]:
import numpy as np

np.__version__

'1.14.0'

In [2]:
np?

CPython is the leading Python implementation. This means that every Python object is a cleverly defined [C structure...](https://github.com/python/cpython/blob/master/Objects/longobject.c)

In [3]:
x = 12345

In [7]:
len(dir(x))

70

In [9]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

With Python's dynamic typing we can also create heterogeneous lists.

In [14]:
L3 = [True, 1, 2.5, None, "some string"]

In [15]:
[type(item) for item in L3]

[bool, int, float, NoneType, str]

## Fixed type arrays

In [17]:
import array

array?

In [18]:
L = list(range(10))

In [19]:
A = array.array("i", L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import numpy as np

In [21]:
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array([3.4, 2, 5, 7.7])

array([3.4, 2. , 5. , 7.7])

In [24]:
np.array([
    range(i, i+3)
    for i in [2, 4, 6]
])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
np.int32, type(np.int32)

(numpy.int32, type)

## Array attributes

In [53]:
arrays = [
    np.random.randint(10, size=6),  # 1D
    np.random.randint(10, size=(3, 4)),  # 2D
    np.random.randint(10, size=(3, 4, 5)),  # 3D
]

for array in arrays:
    print(array.ndim, array.shape, array.size)

1 (6,) 6
2 (3, 4) 12
3 (3, 4, 5) 60


In [54]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[0]

0

In [56]:
a[-1]

9

In [57]:
a[-2]

8

In [58]:
a[-2:]

array([8, 9])

In [61]:
b = np.resize(a, (2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
b[0]

array([0, 1, 2, 3, 4])

In [63]:
b[1]

array([5, 6, 7, 8, 9])

In [64]:
b[0][-2:]

array([3, 4])

In [70]:
np.concatenate((b[0][-2:], b[1][-2:]), axis=0)

array([3, 4, 8, 9])

In [71]:
b[1][2]

7