## Intro to numpy, short for numerical python

In [1]:
import numpy as np

np.__version__

'1.14.0'

In [2]:
np?

CPython is the leading Python implementation. This means that every Python object is a cleverly defined [C structure...](https://github.com/python/cpython/blob/master/Objects/longobject.c)

In [3]:
x = 12345

In [7]:
len(dir(x))

70

In [9]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

With Python's dynamic typing we can also create heterogeneous lists.

In [14]:
L3 = [True, 1, 2.5, None, "some string"]

In [15]:
[type(item) for item in L3]

[bool, int, float, NoneType, str]

## Fixed type arrays

In [17]:
import array

array?

In [18]:
L = list(range(10))

In [19]:
A = array.array("i", L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import numpy as np

In [21]:
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array([3.4, 2, 5, 7.7])

array([3.4, 2. , 5. , 7.7])

In [24]:
np.array([
    range(i, i+3)
    for i in [2, 4, 6]
])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
np.int32, type(np.int32)

(numpy.int32, type)

## Array attributes

In [53]:
arrays = [
    np.random.randint(10, size=6),  # 1D
    np.random.randint(10, size=(3, 4)),  # 2D
    np.random.randint(10, size=(3, 4, 5)),  # 3D
]

for array in arrays:
    print(array.ndim, array.shape, array.size)

1 (6,) 6
2 (3, 4) 12
3 (3, 4, 5) 60


In [54]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[0]

0

In [56]:
a[-1]

9

In [57]:
a[-2]

8

In [58]:
a[-2:]

array([8, 9])

In [61]:
b = np.resize(a, (2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
b[0]

array([0, 1, 2, 3, 4])

In [63]:
b[1]

array([5, 6, 7, 8, 9])

In [64]:
b[0][-2:]

array([3, 4])

In [70]:
np.concatenate((b[0][-2:], b[1][-2:]), axis=0)

array([3, 4, 8, 9])

In [71]:
b[1][2]

7

## Operations

In [72]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.add(a, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
np.subtract(a, 1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [75]:
np.negative(a)

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [76]:
np.divide(a, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [77]:
np.floor_divide(a, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [78]:
np.power(a, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [79]:
np.mod(a, 2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [80]:
np.absolute(np.negative(a))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.sum(a)

45

In [83]:
np.min(a)

0

In [84]:
np.max(a)

9

In [91]:
np.mean(a), np.median(a)

(4.5, 4.5)

***